apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kwg9wetni-python
  janus-idp.io/tekton: kwg9wetni-python
  backstage.io/kubernetes-id: kwg9wetni-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kwg9wetni-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
