apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kwg9wetni-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kwg9wetni-python 
  name: kwg9wetni-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kwg9wetni-python 
